on:
  push:
    paths: ['src/main/java/com/demo/dao/IPersonDao.java', '.github/workflows/work.yaml']
    tags:        
      - v2
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"
